[versions]
annotations = "24.0.0"
logback = "1.5.3"
slf4j = "2.0.12"
mongodb = "5.0.0"
databind = "2.17.0"
javalin = "6.1.3"
json = "20240303"
joda-time = "2.12.7"
bcrypt = "0.10.2"
shadow = "8.1.7"

[libraries]
annontions = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
mongodb-reactive-streams = { group = "org.mongodb", name = "mongodb-driver-reactivestreams", version.ref = "mongodb"}
databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "databind" }
javalin = { group = "io.javalin", name = "javalin", version.ref = "javalin" }
json = { group = "org.json", name = "json", version.ref = "json" }
joda-time = { group = "joda-time", name = "joda-time", version.ref = "joda-time" }
bcrypt = { group = "at.favre.lib", name = "bcrypt", version.ref = "bcrypt" }

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }